version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api
    ports:
      - '3001:3001'
    volumes:
      - '.:/app'
    working_dir: /app
    command: 'npm run start:dev'
    restart: unless-stopped
